--Criado por - Michael Douglas Soares
--Date: 12/06/2018

-- MySQL Script generated by MySQL Workbench
-- ter 12 jun 2018 00:16:58 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema utpmaissaudavel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema utpmaissaudavel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `utpmaissaudavel` DEFAULT CHARACTER SET utf8 ;
USE `utpmaissaudavel` ;

-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`pessoas` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `nome_pessoa` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `sexo` ENUM('M', 'F') NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `codigo` VARCHAR(45) NULL,
  `pessoa_criado_por` INT NOT NULL,
  `pessoa_criado_em` TIMESTAMP NULL,
  `pessoa_atualizado_por` INT NULL,
  `pessoa_atualizado_em` TIMESTAMP NULL,
  PRIMARY KEY (`id_pessoa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabela de Usuários. Referente aos dados pessoais do usuário';


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`enderecos` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `fk_id_pessoa` INT NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NOT NULL,
  `endereco_criado_por` INT NOT NULL,
  `endereco_criado_em` TIMESTAMP NULL,
  `endereco_atualizado_por` INT NULL,
  `endereco_atualizado_em` TIMESTAMP NULL,
  PRIMARY KEY (`id_endereco`, `fk_id_pessoa`),
  INDEX `fk_enderecos_pessoas1_idx` (`fk_id_pessoa` ASC),
  CONSTRAINT `fk_enderecos_pessoas1`
    FOREIGN KEY (`fk_id_pessoa`)
    REFERENCES `utpmaissaudavel`.`pessoas` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabela de endereços de qualquer usuários do sistema.';


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`telefones` (
  `id_telefone` INT NOT NULL AUTO_INCREMENT,
  `fk_id_pessoa` INT NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  `contato` VARCHAR(45) NOT NULL,
  `telefone_criado_por` INT NOT NULL,
  `telefone_criado_em` TIMESTAMP NULL,
  `telefone_atualizado_por` INT NULL,
  `telefone_atualizado_em` TIMESTAMP NULL,
  PRIMARY KEY (`id_telefone`, `fk_id_pessoa`),
  INDEX `fk_telefones_usuarios1_idx` (`fk_id_pessoa` ASC),
  CONSTRAINT `fk_telefones_usuarios1`
    FOREIGN KEY (`fk_id_pessoa`)
    REFERENCES `utpmaissaudavel`.`pessoas` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabela de telefones dos usuários';


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`perfis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`perfis` (
  `id_perfil` INT NOT NULL AUTO_INCREMENT,
  `nome_perfil` VARCHAR(45) NOT NULL,
  `perfil_criado_por` INT NOT NULL,
  `perfil_criado_em` TIMESTAMP NULL,
  `perfil_atualizado_por` INT NULL,
  `perfil_atualizado_em` TIMESTAMP NULL,
  PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabela para Tipos de Perfis';


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`regionais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`regionais` (
  `id_regional` INT NOT NULL AUTO_INCREMENT,
  `nome_regional` VARCHAR(255) NULL,
  `responsavel_regional` VARCHAR(255) NULL,
  `regional_criado_por` INT NULL,
  `regional_criado_em` TIMESTAMP NULL,
  `regional_atualizado_por` INT NULL,
  `regional_atualizado_em` TIMESTAMP NULL,
  PRIMARY KEY (`id_regional`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`unidades_de_saude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`unidades_de_saude` (
  `id_unidade_de_saude` INT NOT NULL AUTO_INCREMENT,
  `fk_id_regional` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `unidade_criado_por` INT NULL,
  `unidade_criado_em` TIMESTAMP NULL,
  `unidade_atualizado_por` INT NULL,
  `unidade_atualizado_em` VARCHAR(45) NULL,
  PRIMARY KEY (`id_unidade_de_saude`, `fk_id_regional`),
  INDEX `fk_unidades_de_saude_regionais1_idx` (`fk_id_regional` ASC),
  CONSTRAINT `fk_unidades_de_saude_regionais1`
    FOREIGN KEY (`fk_id_regional`)
    REFERENCES `utpmaissaudavel`.`regionais` (`id_regional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_lithuanian_ci;


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `fk_id_perfil` INT NOT NULL,
  `fk_id_pessoa` INT NOT NULL,
  `senha` VARCHAR(45) NULL,
  `usuario_criado_por` INT NULL,
  `usuario_criado_em` TIMESTAMP NULL,
  `usuario_atualizado_por` INT NULL,
  `usuario_atualizado_em` TIMESTAMP NULL,
  PRIMARY KEY (`id_usuario`, `fk_id_perfil`, `fk_id_pessoa`),
  INDEX `fk_usuarios_perfis1_idx` (`fk_id_perfil` ASC),
  INDEX `fk_usuarios_pessoas1_idx` (`fk_id_pessoa` ASC),
  CONSTRAINT `fk_usuarios_perfis1`
    FOREIGN KEY (`fk_id_perfil`)
    REFERENCES `utpmaissaudavel`.`perfis` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_pessoas1`
    FOREIGN KEY (`fk_id_pessoa`)
    REFERENCES `utpmaissaudavel`.`pessoas` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`triagem_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`triagem_paciente` (
  `id_triagem_paciente` INT NOT NULL AUTO_INCREMENT,
  `fk_id_paciente` INT NOT NULL,
  `diagnostico_clinico` TEXT NULL,
  `exames_complementares` TEXT NULL,
  `criado_por` INT NOT NULL,
  `criado_em` TIMESTAMP NULL,
  `atualizado_por` INT NULL,
  `atualizado_em` TIMESTAMP NULL,
  PRIMARY KEY (`id_triagem_paciente`, `fk_id_paciente`),
  INDEX `fk_triagem_paciente_pessoas1_idx` (`fk_id_paciente` ASC),
  CONSTRAINT `fk_triagem_paciente_pessoas1`
    FOREIGN KEY (`fk_id_paciente`)
    REFERENCES `utpmaissaudavel`.`pessoas` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`CID10`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`CID10` (
  `id_cid` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = ucs2;


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`agendamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`agendamentos` (
  `id_agendamento` INT NOT NULL AUTO_INCREMENT,
  `data` TIMESTAMP NULL,
  `agendamento_criado_por` INT NULL,
  `agendamento_criado_em` TIMESTAMP NULL,
  `agendamento_atualizado_por` INT NULL,
  `agendamento_atualizado_em` TIMESTAMP NULL,
  PRIMARY KEY (`id_agendamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`pacientes_agendamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`pacientes_agendamentos` (
  `id_paciente_agendamento` INT NOT NULL AUTO_INCREMENT,
  `fk_id_agendamento` INT NOT NULL,
  `fk_id_paciente` INT NOT NULL,
  `p_agendamento_criado_por` INT NULL,
  `p_agendamento_criado_em` TIMESTAMP NULL,
  `p_agendamento_atualizado_por` INT NULL,
  `p_agendamento_atualizado_em` TIMESTAMP NULL,
  PRIMARY KEY (`id_paciente_agendamento`, `fk_id_agendamento`, `fk_id_paciente`),
  INDEX `fk_pacientes_agendamentos_agendamentos1_idx` (`fk_id_agendamento` ASC),
  INDEX `fk_pacientes_agendamentos_usuarios1_idx` (`fk_id_paciente` ASC),
  CONSTRAINT `fk_pacientes_agendamentos_agendamentos1`
    FOREIGN KEY (`fk_id_agendamento`)
    REFERENCES `utpmaissaudavel`.`agendamentos` (`id_agendamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pacientes_agendamentos_usuarios1`
    FOREIGN KEY (`fk_id_paciente`)
    REFERENCES `utpmaissaudavel`.`pessoas` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`especialidades` (
  `id_especialidade` INT NOT NULL AUTO_INCREMENT,
  `especialidade` VARCHAR(255) NULL,
  `descricao` TEXT NULL,
  `especialidade_criado_por` INT NULL,
  `especialidade_criado_em` TIMESTAMP NULL,
  `especialidade_atualizado_por` INT NULL,
  `especialidade_atualizado_em` VARCHAR(45) NULL,
  PRIMARY KEY (`id_especialidade`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`triagem_paciente_especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`triagem_paciente_especialidade` (
  `id_triagem_paciente_especialidade` INT NOT NULL AUTO_INCREMENT,
  `fk_id_especialidade` INT NOT NULL,
  `fk_triagem_paciente` INT NOT NULL,
  `criado_por` INT NULL,
  `criado_em` TIMESTAMP NULL,
  `atualizado_por` INT NULL,
  `atualizado_em` TIMESTAMP NULL,
  PRIMARY KEY (`id_triagem_paciente_especialidade`, `fk_id_especialidade`, `fk_triagem_paciente`),
  INDEX `fk_triagem_paciente_especialidade_especialidades1_idx` (`fk_id_especialidade` ASC),
  INDEX `fk_triagem_paciente_especialidade_triagem_paciente1_idx` (`fk_triagem_paciente` ASC),
  CONSTRAINT `fk_triagem_paciente_especialidade_especialidades1`
    FOREIGN KEY (`fk_id_especialidade`)
    REFERENCES `utpmaissaudavel`.`especialidades` (`id_especialidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_triagem_paciente_especialidade_triagem_paciente1`
    FOREIGN KEY (`fk_triagem_paciente`)
    REFERENCES `utpmaissaudavel`.`triagem_paciente` (`id_triagem_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`profissionais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`profissionais` (
  `id_profissional` INT NOT NULL AUTO_INCREMENT,
  `fk_id_pessoa` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `conselho` VARCHAR(45) NULL,
  `numero_conselho` VARCHAR(45) NULL,
  `profissional_criado_por` INT NULL,
  `profissional_criado_em` TIMESTAMP NULL,
  `profissional_atualizado_por` INT NULL,
  `profissional_atualizado_em` TIMESTAMP NULL,
  PRIMARY KEY (`id_profissional`, `fk_id_pessoa`),
  INDEX `fk_profissionais_pessoas1_idx` (`fk_id_pessoa` ASC),
  CONSTRAINT `fk_profissionais_pessoas1`
    FOREIGN KEY (`fk_id_pessoa`)
    REFERENCES `utpmaissaudavel`.`pessoas` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`historico_saude_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`historico_saude_paciente` (
  `id_historico_saude_paciente` INT NOT NULL AUTO_INCREMENT,
  `fk_triagem_paciente` INT NOT NULL,
  `criado_por` INT NULL,
  `atualizado_por` INT NULL,
  PRIMARY KEY (`id_historico_saude_paciente`, `fk_triagem_paciente`),
  INDEX `fk_historico_saude_paciente_triagem_paciente1_idx` (`fk_triagem_paciente` ASC),
  CONSTRAINT `fk_historico_saude_paciente_triagem_paciente1`
    FOREIGN KEY (`fk_triagem_paciente`)
    REFERENCES `utpmaissaudavel`.`triagem_paciente` (`id_triagem_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`pilares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`pilares` (
  `id_pilar` INT NOT NULL AUTO_INCREMENT,
  `nome_pilar` VARCHAR(255) NULL,
  `criado_por` INT NULL,
  `criado_em` TIMESTAMP NULL,
  `atualizado_por` INT NULL,
  `atualizado_em` TIMESTAMP NULL,
  PRIMARY KEY (`id_pilar`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`perguntas_triagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`perguntas_triagem` (
  `id_perguntas_triagem` INT NOT NULL AUTO_INCREMENT,
  `fk_id_pilar` INT NOT NULL,
  `nome` TEXT NULL,
  `criado_por` INT NULL,
  `criado_em` TIMESTAMP NULL,
  `atualizado_por` INT NULL,
  `atualizado_em` TIMESTAMP NULL,
  PRIMARY KEY (`id_perguntas_triagem`, `fk_id_pilar`),
  INDEX `fk_perguntas_triagem_pilares1_idx` (`fk_id_pilar` ASC),
  CONSTRAINT `fk_perguntas_triagem_pilares1`
    FOREIGN KEY (`fk_id_pilar`)
    REFERENCES `utpmaissaudavel`.`pilares` (`id_pilar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`triagem_paciente_perguntas_fronteira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`triagem_paciente_perguntas_fronteira` (
  `id_triagem_paciente_perguntas_fronteira` INT NOT NULL AUTO_INCREMENT,
  `fk_id_triagem_paciente` INT NOT NULL,
  `fk_id_pergunta_triagem` INT NOT NULL,
  `criado_por` INT NULL,
  `criado_em` TIMESTAMP NULL,
  `atualizado_por` INT NULL,
  PRIMARY KEY (`id_triagem_paciente_perguntas_fronteira`, `fk_id_triagem_paciente`, `fk_id_pergunta_triagem`),
  INDEX `fk_triagem_paciente_perguntas_fronteira_triagem_paciente1_idx` (`fk_id_triagem_paciente` ASC),
  INDEX `fk_triagem_paciente_perguntas_fronteira_perguntas_triagem1_idx` (`fk_id_pergunta_triagem` ASC),
  CONSTRAINT `fk_triagem_paciente_perguntas_fronteira_triagem_paciente1`
    FOREIGN KEY (`fk_id_triagem_paciente`)
    REFERENCES `utpmaissaudavel`.`triagem_paciente` (`id_triagem_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_triagem_paciente_perguntas_fronteira_perguntas_triagem1`
    FOREIGN KEY (`fk_id_pergunta_triagem`)
    REFERENCES `utpmaissaudavel`.`perguntas_triagem` (`id_perguntas_triagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`urls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`urls` (
  `id_url` INT NOT NULL AUTO_INCREMENT,
  `nome_url` VARCHAR(45) NULL,
  `url_criado_por` INT NULL,
  `url_criado_em` TIMESTAMP NULL,
  `url_atualizado_por` INT NULL,
  `url_atualizado_em` TIMESTAMP NULL,
  PRIMARY KEY (`id_url`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`perfis_url`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`perfis_url` (
  `id_perfil_url` INT NOT NULL AUTO_INCREMENT,
  `fk_id_url` INT NOT NULL,
  `fk_id_perfil` INT NOT NULL,
  `p_u_criado_por` INT NULL,
  `p_u_criado_em` TIMESTAMP NULL,
  `p_u_atualizado_por` INT NULL,
  `p_u_atualizado_em` INT NULL,
  PRIMARY KEY (`id_perfil_url`, `fk_id_url`, `fk_id_perfil`),
  INDEX `fk_perfis_url_urls1_idx` (`fk_id_url` ASC),
  INDEX `fk_perfis_url_perfis1_idx` (`fk_id_perfil` ASC),
  CONSTRAINT `fk_perfis_url_urls1`
    FOREIGN KEY (`fk_id_url`)
    REFERENCES `utpmaissaudavel`.`urls` (`id_url`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perfis_url_perfis1`
    FOREIGN KEY (`fk_id_perfil`)
    REFERENCES `utpmaissaudavel`.`perfis` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`dados_pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`dados_pacientes` (
  `id_dados_paciente` INT NOT NULL AUTO_INCREMENT,
  `fk_id_unidade_de_saude` INT NOT NULL,
  `fk_id_paciente` INT NOT NULL,
  `convenio` VARCHAR(45) NULL,
  `responsavel` VARCHAR(45) NULL,
  `dado_paciente_criado_por` INT NULL,
  `dado_paciente_criado_em` TIMESTAMP NULL,
  `dado_paciente_atualizado_por` INT NULL,
  `dado_paciente_atualizado_em` TIMESTAMP NULL,
  PRIMARY KEY (`id_dados_paciente`, `fk_id_unidade_de_saude`, `fk_id_paciente`),
  INDEX `fk_dados_paciente_unidades_de_saude1_idx` (`fk_id_unidade_de_saude` ASC),
  INDEX `fk_dados_paciente_pessoas1_idx` (`fk_id_paciente` ASC),
  CONSTRAINT `fk_dados_paciente_unidades_de_saude1`
    FOREIGN KEY (`fk_id_unidade_de_saude`)
    REFERENCES `utpmaissaudavel`.`unidades_de_saude` (`id_unidade_de_saude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dados_paciente_pessoas1`
    FOREIGN KEY (`fk_id_paciente`)
    REFERENCES `utpmaissaudavel`.`pessoas` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`paciente_especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`paciente_especialidades` (
  `id_paciente_especialidade` INT NOT NULL AUTO_INCREMENT,
  `fk_id_especialidade` INT NOT NULL,
  `fk_id_paciente` INT NOT NULL,
  `p_especialidade_criado_por` INT NULL,
  `p_especialidade_criado_em` TIMESTAMP NULL,
  `p_especialidade_atualizado_por` INT NULL,
  `p_especialidade_atualizado_em` TIMESTAMP NULL,
  PRIMARY KEY (`id_paciente_especialidade`, `fk_id_especialidade`, `fk_id_paciente`),
  INDEX `fk_paciente_especialidades_especialidades1_idx` (`fk_id_especialidade` ASC),
  INDEX `fk_paciente_especialidades_pessoas1_idx` (`fk_id_paciente` ASC),
  CONSTRAINT `fk_paciente_especialidades_especialidades1`
    FOREIGN KEY (`fk_id_especialidade`)
    REFERENCES `utpmaissaudavel`.`especialidades` (`id_especialidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_especialidades_pessoas1`
    FOREIGN KEY (`fk_id_paciente`)
    REFERENCES `utpmaissaudavel`.`pessoas` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`agenda_dias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`agenda_dias` (
  `id_agenda_dias` INT NOT NULL AUTO_INCREMENT,
  `dia_semana` VARCHAR(45) NULL,
  `agenda_dia_criado_por` INT NULL,
  `agenda_dia_criado_em` TIMESTAMP NULL,
  `agenda_dia_atualizado_por` INT NULL,
  `agenda_dia_atualizado_em` TIMESTAMP NULL,
  PRIMARY KEY (`id_agenda_dias`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `utpmaissaudavel`.`agenda_dias_especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utpmaissaudavel`.`agenda_dias_especialidades` (
  `id_agenda_dias_especialidades` INT NOT NULL AUTO_INCREMENT,
  `fk_id_especialidade` INT NOT NULL,
  `fk_id_agenda_dias` INT NOT NULL,
  `data_inicio_agenda` TIMESTAMP NULL,
  `data_fim_agenda` VARCHAR(45) NULL,
  `status` INT NULL,
  `agenda_dias_especialidades_criado_por` INT NULL,
  `agenda_dias_especialidades_criado_em` TIMESTAMP NULL,
  `agenda_dias_especialidades_atualizado_por` INT NULL,
  `agenda_dias_especialidades_atualizado_em` TIMESTAMP NULL,
  PRIMARY KEY (`id_agenda_dias_especialidades`, `fk_id_especialidade`, `fk_id_agenda_dias`),
  INDEX `fk_agenda_dias_especialidades_especialidades1_idx` (`fk_id_especialidade` ASC),
  INDEX `fk_agenda_dias_especialidades_agenda_dias1_idx` (`fk_id_agenda_dias` ASC),
  CONSTRAINT `fk_agenda_dias_especialidades_especialidades1`
    FOREIGN KEY (`fk_id_especialidade`)
    REFERENCES `utpmaissaudavel`.`especialidades` (`id_especialidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_dias_especialidades_agenda_dias1`
    FOREIGN KEY (`fk_id_agenda_dias`)
    REFERENCES `utpmaissaudavel`.`agenda_dias` (`id_agenda_dias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
